[package]
name = "libtexsyn"
version = "0.1.0"
authors = ["R.Chavignat <r.chavignat@gmail.com>"]

[dependencies]
approx = "^0.1.1"
conv = "^0.3.3"
error-chain = "^0.10.0"
imageproc = "^0.7.0"
image = "^0.12.3"
num-traits = "^0.1.36"
rand = "^0.3.15"
rayon = "^0.6.0"
term = "^0.4.5"
