[package]
name = "libtexsyn"
version = "0.1.0"
authors = ["R.Chavignat <r.chavignat@gmail.com>"]

[dependencies]
approx = "^0.1.1"
conv = "^0.3.3"
error-chain = "^0.10.0"
imageproc = "^0.8.0"
image = "^0.13.0"
num-traits = "^0.1.39"
rand = "^0.3.15"
rayon = "^0.8.1"
term = "^0.4.5"
